server {
  listen 443 ssl http2;
  server_name box.io;

  ssl_certificate     /etc/ssl/cloudflare/box.io.crt;
  ssl_certificate_key /etc/ssl/cloudflare/box.io.key;

  access_log /var/log/nginx/box_access.log;
  error_log  /var/log/nginx/box_error.log;

  # --- Landing page ---
  root /var/www/landing;
  index index.html;

  # location = /index.html {
  #  add_header Cache-Control "no-store, no-cache, must-revalidate, max-age=0" always;
  #  add_header Pragma "no-cache" always;
  #  add_header Expires "0" always;
  #  try_files $uri =404;
  #}


  # --- React app under /hive-planner/ ---
  location /hive-planner {
    alias /srv/apps/hive-planner/hive-planner-ui/current/;
    index index.html;
    try_files $uri $uri/ /hive-planner/index.html;

    # optional basic auth
    #auth_basic "Hive Planner Login";
    #auth_basic_user_file /etc/nginx/.htpasswd;
  }
  #  location ~* ^/hive-planner/.*\.(?:css|js|mjs|map|ico|svg|png|jpg|jpeg|gif|webp|woff2?|ttf|otf)$ {
  #  try_files $uri =404;   # nikad ne vracaj index.html za assete
  #  expires 1y;
  #  access_log off;
  #}

  #(Optional) no-cache for the app HTML so deploys go live immediately
  location = /hive-planner/index.html {
    alias /srv/apps/hive-planner/hive-planner-ui/current/index.html;
    add_header Cache-Control "no-store, no-cache, must-revalidate, max-age=0" always;
    add_header Pragma "no-cache" always;
    add_header Expires "0" always;
  }


  # --- API under /api/ -> Kestrel (.NET) ---
  location /api/ {
      #allow 203.0.113.25;   # your static IP
      #allow 203.0.113.25; 
      #deny all;

      proxy_pass http://127.0.0.1:5000;
      proxy_http_version 1.1;
 
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;

      # Basic Auth protection
      #auth_basic "Hive Planner API";
      #auth_basic_user_file /etc/nginx/.htpasswd;

     # CORS headers
      add_header Access-Control-Allow-Origin "https://box.io" always;
      add_header Access-Control-Allow-Credentials true always;
      add_header Access-Control-Allow-Methods "GET, POST, PUT, DELETE, OPTIONS" always;
      add_header Access-Control-Allow-Headers "Authorization, Content-Type" always;

      # Handle preflight requests directly
      if ($request_method = OPTIONS) {
          add_header Access-Control-Allow-Origin "https://box.io";
          add_header Access-Control-Allow-Credentials true;
          add_header Access-Control-Allow-Methods "GET, POST, PUT, DELETE, OPTIONS";
          add_header Access-Control-Allow-Headers "Authorization, Content-Type";
          return 204;
      }
  }
  location /api/swagger {
    # optional basic auth
    auth_basic "Hive Planner Login";
    auth_basic_user_file /etc/nginx/.htpasswd;

    proxy_pass http://127.0.0.1:5000/swagger;
  }


}

server {
  listen 80;
  server_name box.io;
  return 301 https://$host$request_uri;
}

